// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaEWng0Hm7MK_eGrFcO3_CnHuvEVLjZqw',
    appId: '1:785419564711:web:9a79f462f186a70437cd82',
    messagingSenderId: '785419564711',
    projectId: 'bookswap-71e05',
    authDomain: 'bookswap-71e05.firebaseapp.com',
    storageBucket: 'bookswap-71e05.firebasestorage.app',
    measurementId: 'G-PYVVHDDE1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzVGeVwh6SZvWcqmljb6HKTmlfe4s1tNo',
    appId: '1:785419564711:android:a9f6aa4c58d87b6237cd82',
    messagingSenderId: '785419564711',
    projectId: 'bookswap-71e05',
    storageBucket: 'bookswap-71e05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD231NTGbKHWT3PCJY4SOaBAqielSsNWvQ',
    appId: '1:785419564711:ios:677c18eaca25c8fd37cd82',
    messagingSenderId: '785419564711',
    projectId: 'bookswap-71e05',
    storageBucket: 'bookswap-71e05.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD231NTGbKHWT3PCJY4SOaBAqielSsNWvQ',
    appId: '1:785419564711:ios:677c18eaca25c8fd37cd82',
    messagingSenderId: '785419564711',
    projectId: 'bookswap-71e05',
    storageBucket: 'bookswap-71e05.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaEWng0Hm7MK_eGrFcO3_CnHuvEVLjZqw',
    appId: '1:785419564711:web:7b93ee24f06b064337cd82',
    messagingSenderId: '785419564711',
    projectId: 'bookswap-71e05',
    authDomain: 'bookswap-71e05.firebaseapp.com',
    storageBucket: 'bookswap-71e05.firebasestorage.app',
    measurementId: 'G-KR0NX25SR3',
  );
}
